In [38]:
import torch
import torch.nn.functional as F
torch.manual_seed(42)

Z = torch.randint(-5, 6, (1, 1, 3, 3), dtype=torch.float32, requires_grad=True)
W = torch.randint(-3, 4, (1, 1, 2, 2), dtype=torch.float32, requires_grad=True)

A = F.conv2d(Z, W)
dA = torch.randint(-3, 3, A.shape, dtype=torch.float32)
A.backward(dA)

In [39]:
dA, Z, W

(tensor([[[[-3.,  0.],
           [ 1.,  2.]]]]),
 tensor([[[[ 1.,  2.,  4.],
           [-2., -3.,  5.],
           [-2., -5.,  3.]]]], requires_grad=True),
 tensor([[[[-3., -3.],
           [ 2.,  3.]]]], requires_grad=True))

In [40]:
print("dZ = ∂L/∂Z:\n", Z.grad)
print("dW = ∂L/∂W:\n", W.grad)

dZ = ∂L/∂Z:
 tensor([[[[  9.,   9.,   0.],
          [ -9., -18.,  -6.],
          [  2.,   7.,   6.]]]])
dW = ∂L/∂W:
 tensor([[[[-11.,   1.],
          [ -6.,  10.]]]])
